---
# tasks file for ansible
- name: Update apt cache
  apt:
    update_cache: yes
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version == "20.04"
    - ansible_distribution_file_variety == "Debian" 

- name: Install System dependencies for Ubuntu
  apt:
    update_cache: no
    pkg:
      - ansible
      - git
  run_once: true
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version == "20.04"
    - ansible_distribution_file_variety == "Debian" 

- name: Ansible  roles dir creation
  file:
    path: "{{ path_to_roles }}"
    state: directory
    mode: '0750'

- name: Ansible requirements for roles 
  copy:
    src: requirements.yml
    dest: "{{ path_to_requirements }}"


- name: Ansible requirements for roles 
  become_user: ansible
  become_user: true
  command: "ansible-galaxy role install --role-file {{ path_to_requirements }}   --roles-path {{ path_to_roles }}" 


- name: Ansible private-keys for hosts
  become_user: ansible
  become_user: true
  copy:
    src: "{{ src_private_key }}"
    dest: "{{ path_to_key }}"
    mode: '0600'

- name: Autoclean apt cache
  apt:
    autoclean: yes
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version == "20.04"
    - ansible_distribution_file_variety == "Debian" 

- name: Autoremove apt dependencies
  apt:
    autoremove: yes
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version == "20.04"
    - ansible_distribution_file_variety == "Debian" 